### ISSUE TITLE
Locales with capitalized region not working

### ISSUE THREAD

**Issue by beeb** [bart-krakowski/get-week-info-polyfill#3]
I think there is a bug where this line makes it so `en-GB` for example doesn't work, and uses `en` instead:

https://github.com/bart-krakowski/get-week-info-polyfill/blob/3db808ca252c2210127b82ed90b54365a9a3bd77/src/index.ts#L12

Can you elaborate why you perform `toLowerCase` here?

Also I forgot to add a `default` key to the mapping in my PR so the fallback is probably not working either.

Maybe time to add unit tests haha

**Comment by bart-krakowski** [comment]
I improved this logic a little bit. In general this logic is to ignore casing, eg. `en-aU`, `en-Au` `en-au` etc.
I definitely have to add some tests
